[versions]
agp = "8.11.2"
androidxJunit = "1.3.0"
cardview = "1.0.0"
converterGson = "3.0.0"
coordinatorlayout = "1.3.0"
core = "1.17.0"
espressoCoreVersion = "3.7.0"
firebaseBom = "34.7.0"
firebaseBomVersion = "34.7.0"
firebaseDatabaseKtx = "22.0.1"
generativeai = "0.9.0"
generativeaiVersion = "0.9.0"
guava = "33.5.0-android"
guavaVersion = "33.5.0-android"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
lifecycleExtensions = "2.2.0"
lifecycleLivedata = "2.10.0"
lifecycleRuntime = "2.10.0"
lifecycleViewmodel = "2.10.0"
loggingInterceptor = "5.3.2"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
materialVersion = "1.13.0"
okhttp = "5.3.2"
picasso = "2.71828"
playServicesAuth = "21.4.0"
playServicesLocation = "21.3.0"
playServicesLocationVersion = "21.3.0"
playServicesMaps = "19.2.0"
recyclerview = "1.4.0"
retrofitVersion = "3.0.0"
secretsGradlePlugin = "2.0.1"
espressoWeb = "3.7.0"
timelineview = "1.2.2"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
volley = "1.2.1"

[libraries]
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core = { module = "androidx.core:core", version.ref = "core" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-bom-v3270 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabaseKtx" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
generativeai-v012 = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeaiVersion" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
google-firebase-database = { module = "com.google.firebase:firebase-database" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guava-v3350android = { module = "com.google.guava:guava", version.ref = "guavaVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleLivedata" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleRuntime" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v130alpha02 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-location-v2110 = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
espresso-web = { group = "androidx.test.espresso", name = "espresso-web", version.ref = "espressoWeb" }
timelineview = { module = "com.github.vipulasri:timelineview", version.ref = "timelineview" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

